### ISSUE TITLE
C2_W2_Assignment: Part of Speech Tagging, accurancy is not match

### ISSUE THREAD

**Issue by ijelliti** [ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization#14]
In ,the Accuracy of the Viterbi algorithm is **0.9528** while the expected is **0.9531**
despite the difference is small 0.0003, the autograder consider it wrong accuracy.

![image](https://user-images.githubusercontent.com/9965888/85830180-1559e380-b784-11ea-9bdc-c5010f5d0a64.png)

output from the autograder:

>  Code Cell UNQ_C8: Function 'compute_accuracy' is incorrect. Check implementation.

**Comment by adeepH** [comment]
![fix](https://user-images.githubusercontent.com/46108405/86370337-38f9be00-bc9d-11ea-8158-b521195346bb.PNG)

there is a mistake in the compute_accuracy function you had defined.please find the correct code as a snip because I needed to show you the accuracy herr

**Comment by ijelliti** [comment]
@adeepH 
thanks for you answer, I tried your code, but it give me the same result **0.9528**

![image](https://user-images.githubusercontent.com/9965888/86374080-0f7c6a80-bc7c-11ea-93f9-3c41dba349f4.png)

**Comment by adeepH** [comment]
@ijelliti  C7 has the function **viterbi forward**  which returns  **Pred**. This is used in  C8 **complete Accuracy**.
Please check if your code matches with what I've written.
![ded](https://user-images.githubusercontent.com/46108405/86436302-9fbfbb80-bd1f-11ea-99df-c6052e824355.PNG)

**Comment by ijelliti** [comment]
@adeepH this implementation of C7 doesn't give the same expected output.

**Comment by ijelliti** [comment]
good job @adeepH, I just make a double check and it give me the accuracy **0.9531** 
that's perfect you resolved the issue

**Comment by ijelliti** [comment]
@adeepH please add a pr on your solution to the project so we can merge it to the master c2_w2 assignment notebook.
