### ISSUE TITLE
utils.py not included

### ISSUE THREAD

**Issue by hailiangliu89** [ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization#16]
Hi First, thank you very much for sharing your solutions.

I noticed in some notebooks we need to call functions defined in the module/script called utils. I am wondering if we can find that script anywhere in the repo? It seems it can not be found if we run the notebook on a local machine.

Thanks again!

**Comment by ijelliti** [comment]
Hi @hailiangliu89,

Thanks for bringing this up. I managed to get all dependencies for course 1 and 2 and merged them to the master
If your refresh your master you should be able to run the notebooks on your local jupyter server.

Thanks,
Ibrahim

**Comment by andreian02** [comment]
Hello ijelliti, 

Thank you for sharing the materials, I didnt want to open another issue for this but you would be able to kindly share the logistic_features.csv file which is used in the labs on logistic regression? 

Thank you!

**Comment by ijelliti** [comment]
Hello @andreian02,

thanks for catching this, I added the required file of the lab into a separate branch. I opened a PR for it, kindly review it if  it works for you locally and everything looks good we can merge it to the master.

Thank you,
Ibrahim

**Comment by ijelliti** [comment]
@hailiangliu89  I think the issue of missed labs and assigmnets files is resolved.
@andreian02 I am closing this for #22

**Comment by andreian02** [comment]
Thank you very much!
