### ISSUE TITLE
add 'logistic_features.csv'

### ISSUE THREAD

**Issue by tsuirak** [ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization#22]
In 1 - Natural Language Processing with Classification and Vector Spaces - Labs - Week1 - NLP_C1_W1_lecture_nb_03.ipynb.

There is no 'logistic_features.csv'.

**Comment by ijelliti** [comment]
hi @tsuirak, this missed csv file is added in sperate branch, I opened for it a PR.

**Comment by ijelliti** [comment]
I merged the PR to the master.
the required file is now available in the master.

**Comment by tsuirak** [comment]
ok thanks




| |
RoseXIN
|
|
rosexin13@yeah.net
|

Signature is customized by Netease Mail Master

On 07/02/2020 19:50, Ibrahim wrote:

I merged the PR to the master.
the required file is now available in the master.
