### ISSUE TITLE
NLP_C1_W2_lecture_nb_01 

### ISSUE THREAD

**Issue by tsuirak** [ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization#23]
Sorry, I can't find this csv.
'bayes_features.csv'.

**Comment by ijelliti** [comment]
file added.
https://github.com/ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization/blob/master/1 - Natural Language Processing with Classification and Vector Spaces/Labs/Week 2/bayes_features.csv
