### ISSUE TITLE
Please add result table after laplasian smoothing 

### ISSUE THREAD

**Issue by jdixosnd** [ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization#46]
In course 1, second week notes,
The concept of laplasian smoothing is discussed, but the result table is not there.. 
Please add following table to make it more intuitive.
![Screenshot from 2020-07-11 12-40-36](https://user-images.githubusercontent.com/11541260/87218813-d3c85b80-c373-11ea-8b9f-94372749b275.png)

**Comment by ijelliti** [comment]
@jdixosnd please review the PR if it sounds good to merge it.
thanks,
Ibrahim
