### ISSUE TITLE
Course 3 is online now, upload the code ?

### ISSUE THREAD

**Issue by stayrea1** [ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization#50]
Course 3  started yesterday, can you upload the init code? Thank you!

**Comment by ijelliti** [comment]
hello @stayrea1,
I just upload W1 assignments, I will upload the following weeks.

thanks
Ibrahim

**Comment by stayrea1** [comment]
Thanks bro, the original assignment you upload is awesome!
