### ISSUE TITLE
Can you add course 3 week2 ungraded labs？

### ISSUE THREAD

**Issue by linhanxiao** [ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization#59]
Can you add course 3 week2 ungraded labs？I didn't find the ungraded labs in course3 week2 directory. @ijelliti

**Comment by ijelliti** [comment]
@linhanxiao I uploaded them yesterday but in Week 3 folder. so now the ungraded labs are in the right folder.

**Comment by linhanxiao** [comment]
Thanks for replying so quickly  @ijelliti
