### ISSUE TITLE
Course 2 week 4 ~ Wrong back propagation function ~ UNQ_C4

### ISSUE THREAD

**Issue by dzerkes** [ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization#64]
On the 2nd course of the specialization on the assignment of the week 4 there is a mistake on the back-propagation calculation on the section 'UNQ_C4'

You calculate the gradient of biases wrong. You should change it as follows:

```
grad_b1 = (1/batch_size)*np.dot(l1,ones_array.T).reshape(-1,1)

grad_b2 = (1/batch_size)*np.dot(yhat-y,ones_array.T).reshape(-1,1)
```

where

` ones_array = np.ones(batch_size)`

With that way it is the same as the slides in the course. You can check your own notes too on this github repository of how gradient of bias should be calculated.

**Comment by ijelliti** [comment]
Hi @dzerkes,
that seems another way to calculate the gradients and all are correct.
![image](https://github.com/ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization/raw/master/2%20-%20Natural%20Language%20Processing%20with%20Probabilistic%20Models/Images/54.png)
we can do your way, other do it like this: 
```
    # Compute the gradient of b2
    grad_b1 = np.dot(l1,np.ones((batch_size,1)))/batch_size
    # Compute the gradient of b2
    grad_b2 = np.dot((yhat - y),np.ones((batch_size,1)))/batch_size
```
in my notebook I used
```
    # Compute the gradient of b1
    grad_b1 = np.sum((1/batch_size)*np.dot(l1,x.T),axis=1,keepdims=True)
    # Compute the gradient of b2
    grad_b2 = np.sum((1/batch_size)*np.dot(yhat-y,h.T),axis=1,keepdims=True)
```
as in python snippet from te lecture slide picture above.

**Comment by dzerkes** [comment]
Yes I notice, just in that way it does not count it as wrong and has the same outputs as it expects.
