### ISSUE TITLE
can you upload  the  ungraded notebook in course4 week4？

### ISSUE THREAD

**Issue by linhanxiao** [ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization#69]
can you upload  the  ungraded notebook in course4 week4？the  Ungraded Lab: Reformer LSH notebook and  the Ungraded Lab: Revnet notebook @ijelliti

**Comment by ijelliti** [comment]
@linhanxiao, I uploaded the two labs
[C4_W4_Ungraded_Lab_Reformer_LSH.ipynb](https://github.com/ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization/blob/master/4%20-%20Natural%20Language%20Processing%20with%20Attention%20Models/Labs/Week%204/C4_W4_Ungraded_Lab_Reformer_LSH.ipynb)
[C4_W4_Ungraded_Lab_Revnet.ipynb](https://github.com/ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization/blob/master/4%20-%20Natural%20Language%20Processing%20with%20Attention%20Models/Labs/Week%204/C4_W4_Ungraded_Lab_Revnet.ipynb)

**Comment by linhanxiao** [comment]
Thanks for replying so quickly @ijelliti
